apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
imageRepository: container-registry.oracle.com/olcne
kubernetesVersion: 1.24.8
etcd:
  local:
    imageRepository: container-registry.oracle.com/olcne
    imageTag: 3.5.3
dns:
  imageRepository: container-registry.oracle.com/olcne
  imageTag: 1.8.3
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/crio/crio.sock