apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
imageRepository: container-registry.oracle.com/olcne
kubernetesVersion: k8s_version
etcd:
  local:
    imageRepository: container-registry.oracle.com/olcne
    imageTag: etcd_image_tag
dns:
  imageRepository: container-registry.oracle.com/olcne
  imageTag: dns_image_tag
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/crio/crio.sock