apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
imageRepository: container-registry.oracle.com/olcne
kubernetesVersion: 1.26.6
etcd:
  local:
    imageRepository: container-registry.oracle.com/olcne
    imageTag: 3.5.6
dns:
  imageRepository: container-registry.oracle.com/olcne
  imageTag: v1.9.3
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
